-- AlterEnum
ALTER TYPE "WorkerBucket" ADD VALUE IF NOT EXISTS 'PROVIDENT_FUND';
ALTER TYPE "WorkerTxnKind" ADD VALUE IF NOT EXISTS 'SALARY_PAYOUT';
ALTER TYPE "WorkerTxnKind" ADD VALUE IF NOT EXISTS 'PF_CONTRIBUTION';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "providentFund" DECIMAL(12,2) NOT NULL DEFAULT 0;
