export const editableEnvKeys = [
  "DATABASE_URL",
  "DIRECT_URL",
  "AUTH_SECRET",
  "NEXTAUTH_SECRET",
  "NEXT_PUBLIC_APP_URL",
  "RESEND_API_KEY",
  "EMAIL_FROM",
  "PUSHER_APP_ID",
  "PUSHER_SECRET",
  "NEXT_PUBLIC_PUSHER_KEY",
  "NEXT_PUBLIC_PUSHER_CLUSTER",
  "BLOB_READ_WRITE_TOKEN",
  "CRON_SECRET",
  "WHATSAPP_ENABLED",
  "WHATSAPP_ACCESS_TOKEN",
  "WHATSAPP_PHONE_NUMBER_ID",
  "WHATSAPP_GRAPH_VERSION",
  "WHATSAPP_OTP_ENABLED",
  "WHATSAPP_NOTIFICATIONS_ENABLED",
] as const;

export type EditableEnvKey = (typeof editableEnvKeys)[number];
