import type { LandingReviewData } from "@/lib/landing-data";

/**
 * Reviews clients actually left on the marketplaces.
 *
 * Transcribed from the Fiverr profile on 3 August 2026. Buyer handle, country,
 * star rating and wording are exactly as published there — nothing is
 * paraphrased or rounded, because the whole value of these is that a visitor
 * can go and find the same words on Fiverr.
 *
 * Handles rather than real names: that is what the marketplace shows, and it
 * is what makes them checkable. A buyer who left two reviews appears twice,
 * marked as a repeat client, which is worth more than either review alone.
 */
export const marketplaceReviews: LandingReviewData[] = [
  {
    id: "fiverr-grow71",
    clientName: "grow71",
    clientRole: "",
    company: "",
    country: "Australia",
    rating: 5,
    quote:
      "Delivered great work. Clear communication, fast turnaround, and high-quality output. Very Professional, quick, and accurate. The job was done better than expected and ahead of time. I'll use this seller again.",
    details: "Fiverr · $800–$1,000 · delivered over 2 months",
    avatarUrl: "",
    service: "UI/UX Design",
    orderNumber: 2,
  },
  {
    id: "fiverr-sb-corporation-hotel",
    clientName: "sb_corporation",
    clientRole: "",
    company: "",
    country: "United States",
    rating: 5,
    quote:
      "We hired them for a website redesign for our hotel in Victoria, BC, and they did an outstanding job. The pricing was fair, and communication was excellent. They were always available to answer our questions. The design itself was modern, with a great sense of color, layout, spacing, and visual hierarchy.",
    details: "Fiverr · up to $50 · delivered in 2 days",
    avatarUrl: "",
    service: "UI/UX Design",
    orderNumber: 2,
  },
  {
    id: "fiverr-jasonmery",
    clientName: "jasonmery",
    clientRole: "",
    company: "",
    country: "United Kingdom",
    rating: 5,
    quote:
      "Working with Nahida was an absolute pleasure. She delivered my urgent project in just 3 hours without compromising on quality. The design was creative and exceeded my expectations. I'm truly impressed and would definitely recommend her services to anyone in need of top-notch work!",
    details: "Fiverr · $50–$100 · delivered in 6 days",
    avatarUrl: "",
    service: "UI/UX Design",
  },
  {
    id: "fiverr-sb-corporation",
    clientName: "sb_corporation",
    clientRole: "",
    company: "",
    country: "United States",
    rating: 5,
    quote:
      "Working with Nahida was an absolute pleasure. Her work in website design didn't just meet the brief but exceeded expectations, showing a level of cooperation that truly set the project up for success. An amazing experience all around!",
    details: "Fiverr · $100–$200 · delivered in 4 days",
    avatarUrl: "",
    service: "UI/UX Design",
    orderNumber: 2,
  },
  {
    id: "fiverr-davidson4608",
    clientName: "davidson4608",
    clientRole: "",
    company: "",
    country: "United States",
    rating: 5,
    quote:
      "It was a great experience working with Nahida. She delivered my urgent project within just 3 hours, and the design was outstanding. I highly recommend everyone try her services.",
    details: "Fiverr · $200–$400 · delivered in 1 day",
    avatarUrl: "",
    service: "UI/UX Design",
  },
  {
    id: "fiverr-robertphilip807",
    clientName: "robertphilip807",
    clientRole: "",
    company: "",
    country: "United Kingdom",
    rating: 5,
    quote:
      "She is a very talented designer, super patient, she works very fast and got the job done to what you're trying to accomplish. Very helpful to make the website screens. I would definitely recommend using her to design and I look forward to working with you in the future, thank you.",
    details: "Fiverr · $50–$100 · delivered in 6 days",
    avatarUrl: "",
    service: "UI/UX Design",
    orderNumber: 2,
  },
  {
    id: "fiverr-talkhoward632",
    clientName: "talkhoward632",
    clientRole: "",
    company: "",
    country: "United States",
    rating: 5,
    quote:
      "Very professional and helpful seller. They asked the right questions, understood my vision, and delivered a great outcome. Would recommend to others.",
    details: "Fiverr · $100–$200 · delivered in 7 days",
    avatarUrl: "",
    service: "UI/UX Design",
  },
  {
    id: "fiverr-anselmhubert-detail",
    clientName: "anselmhubert",
    clientRole: "",
    company: "",
    country: "Spain",
    rating: 5,
    quote:
      "The seller delivered high-quality UI/UX design with attention to detail, maintaining a clean and user-friendly interface that met all expectations.",
    details: "Fiverr · up to $50 · delivered in 6 days",
    avatarUrl: "",
    service: "UI/UX Design",
    orderNumber: 3,
  },
  {
    id: "fiverr-abayakimon",
    clientName: "abayakimon",
    clientRole: "",
    company: "",
    country: "United Kingdom",
    rating: 5,
    quote:
      "Excellent service! They understood my requirements clearly and delivered exactly what I needed. Very supportive even after delivery, which makes a big difference. Highly recommended.",
    details: "Fiverr · $50–$100 · delivered in 3 days",
    avatarUrl: "",
    service: "UI/UX Design",
  },
  {
    id: "fiverr-tech-angecy",
    clientName: "tech_angecy",
    clientRole: "",
    company: "",
    country: "Malaysia",
    rating: 5,
    quote:
      "Very smooth process, great creativity, and timely delivery. Would work again.",
    details: "Fiverr · $100–$200 · delivered in 7 days",
    avatarUrl: "",
    service: "UI/UX Design",
    orderNumber: 2,
  },
  {
    id: "fiverr-maxidiomalinda",
    clientName: "maxidiomalinda",
    clientRole: "",
    company: "",
    country: "France",
    rating: 5,
    quote:
      "Excellent professionalism and great design skills. I highly recommend this seller to others.",
    details: "Fiverr · $100–$200 · delivered in 4 days",
    avatarUrl: "",
    service: "UI/UX Design",
  },
  {
    id: "fiverr-romahouston",
    clientName: "romahouston",
    clientRole: "",
    company: "",
    country: "United States",
    rating: 5,
    quote:
      "The seller delivered excellent work on time and maintained clear communication. I am satisfied with the service and would highly recommend them.",
    details: "Fiverr · $50–$100 · delivered in 4 days",
    avatarUrl: "",
    service: "UI/UX Design",
  },
  {
    id: "fiverr-anselmhubert-reliable",
    clientName: "anselmhubert",
    clientRole: "",
    company: "",
    country: "Spain",
    rating: 5,
    quote:
      "Great job! Everything was done as discussed. Reliable, skilled, and a pleasure to work with. Would hire again.",
    details: "Fiverr · up to $50 · delivered in 4 days",
    avatarUrl: "",
    service: "UI/UX Design",
    orderNumber: 2,
  },
  {
    id: "fiverr-henneshudson",
    clientName: "henneshudson",
    clientRole: "",
    company: "",
    country: "United States",
    rating: 5,
    quote:
      "Consistent quality, fast delivery, and clear communication. Highly recommended.",
    details: "Fiverr · $50–$100 · delivered in 5 days",
    avatarUrl: "",
    service: "UI/UX Design",
  },
  {
    id: "fiverr-ashleyandreas",
    clientName: "ashleyandreas",
    clientRole: "",
    company: "",
    country: "United States",
    rating: 5,
    quote:
      "Very professional and helpful seller. They asked the right questions, understood my vision, and delivered a great outcome.",
    details: "Fiverr · $50–$100 · delivered in 4 days",
    avatarUrl: "",
    service: "UI/UX Design",
  },
  {
    id: "fiverr-alexanderbrof88",
    clientName: "alexanderbrof88",
    clientRole: "",
    company: "",
    country: "United States",
    rating: 5,
    quote:
      "Excellent job! The posts, captions, and highlight covers were top-notch. My bio looks much better too. Thank you for the timely delivery.",
    details: "Fiverr · $50–$100 · delivered in 6 days",
    avatarUrl: "",
    service: "Graphics Design",
    orderNumber: 2,
  },
  {
    id: "fiverr-anselmhubert-responsive",
    clientName: "anselmhubert",
    clientRole: "",
    company: "",
    country: "Spain",
    rating: 5,
    quote:
      "The seller was professional, responsive, and delivered high-quality work on time.",
    details: "Fiverr · $50–$100 · delivered in 4 days",
    avatarUrl: "",
    service: "UI/UX Design",
    orderNumber: 2,
  },
  {
    id: "fiverr-davidkartu",
    clientName: "davidkartu",
    clientRole: "",
    company: "",
    country: "France",
    rating: 5,
    quote: "I enjoyed working with Nahida and will again.",
    details: "Fiverr · $100–$200 · delivered in 1 day",
    avatarUrl: "",
    service: "UI/UX Design",
    orderNumber: 2,
  },
  {
    id: "fiverr-lakelandchfer",
    clientName: "lakelandchfer",
    clientRole: "",
    company: "",
    country: "United Kingdom",
    rating: 5,
    quote: "You are a professional seller. Thank you so much for the work.",
    details: "Fiverr · $100–$200 · delivered in 8 days",
    avatarUrl: "",
    service: "UI/UX Design",
    orderNumber: 2,
  },
];
